### ISSUE TITLE
compiling to Android works, however the app crashes at startup

### ISSUE THREAD

**Issue by stefan52a** [commerceblock/cb-client-wallet#20]
Use instructions at
https://www.reddit.com/r/Electrum/comments/akxh5o/how_to_compile_an_electrum_testnet_apk/
After installing the docker, also copy from
Git clone https://github.com/spesmilo/electrum.git
cp -r  /home/stefan/Downloads//electrum/electrum/gui gui/         
then
docker run -it --rm     --name electrum-android-builder-cont    -v $PWD:/home/user/wspace/electrum     -v ~/.keystore:/home/user/.keystore    --workdir /home/user/wspace/electrum     electrum-android-builder-img     ./contrib/make_apk    
compiles
to an apk (see attachment).

However it crashes on my androids ;(
[Electrum-4.0.0.0-debug.zip](https://github.com/commerceblock/cb-client-wallet/files/3162012/Electrum-4.0.0.0-debug.zip)

**Comment by nkostoulas** [comment]
Are you trying this with electrum or cb-client-wallet? Any error logs you can share?

**Comment by stefan52a** [comment]
Compiled using instructions of https://www.reddit.com/r/Electrum/comments/akxh5o/how_to_compile_an_electrum_testnet_apk/  (they are more up-to-date) 
compiled cb-client-wallet

Error, (selected from logcat):

05-09 15:58:00.348  3925  3975 E WindowManager: RemoteException occurs on reporting focusChanged, w=Window{4d379b4 u0 org.electrum.electrum/org.kivy.android.PythonActivity}
05-09 15:58:00.348  3925  3975 E WindowManager: android.os.DeadObjectException
05-09 15:58:00.348  3925  3975 E WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
05-09 15:58:00.348  3925  3975 E WindowManager: 	at android.os.BinderProxy.transact(Binder.java:1143)
05-09 15:58:00.348  3925  3975 E WindowManager: 	at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:500)
05-09 15:58:00.348  3925  3975 E WindowManager: 	at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3879)
05-09 15:58:00.348  3925  3975 E WindowManager: 	at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5426)
05-09 15:58:00.348  3925  3975 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-09 15:58:00.348  3925  3975 E WindowManager: 	at android.os.Looper.loop(Looper.java:214)
05-09 15:58:00.348  3925  3975 E WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:65)
05-09 15:58:00.348  3925  3975 E WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
05-09 15:58:00.351  5258  5258 D PageOverlayMover: updateActivityLifecycleState : 1
05-09 15:58:00.351  5258  5258 D ViewRootImpl@318cc9a[LauncherActivity]: setWindowStopped(false) old=false
05-09 15:58:00.351  5258  5258 V Launcher: Launcher.onResume()

Now I think of it, maybe we need to set testnet:
https://www.reddit.com/r/Electrum/comments/akxh5o/how_to_compile_an_electrum_testnet_apk/

**Comment by nkostoulas** [comment]
Not sure sorry, we currently don't support an Android version. You might want to check with upstream electrum.
