### ISSUE TITLE
Transaction Data Error

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/cb-client-wallet#32]
Error ocurs when double clicking on a transaction - e.g. redemption transaction

in <genexpr>
    return sum(x['value'] for x in self.inputs())
KeyError: 'value'
Traceback (most recent call last):
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/history_list.py", line 302, in on_doubleclick
    self.parent.show_transaction(tx)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/main_window.py", line 810, in show_transaction
    show_transaction(tx, self, tx_desc)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/transaction_dialog.py", line 57, in show_transaction
    d = TxDialog(tx, parent, desc, prompt_if_unsaved)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/transaction_dialog.py", line 163, in __init__
    self.update()
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/transaction_dialog.py", line 256, in update
    fee = self.tx.get_fee()
  File "/Users/cryptopoly/cb-client-wallet/electrum/transaction.py", line 1153, in get_fee
    return self.input_value() - self.output_value()
  File "/Users/cryptopoly/cb-client-wallet/electrum/transaction.py", line 1140, in input_value
    return sum(x['value'] for x in self.inputs())
  File "/Users/cryptopoly/cb-client-wallet/electrum/transaction.py", line 1140, in <genexpr>
    return sum(x['value'] for x in self.inputs())
KeyError: 'value'
Traceback (most recent call last):
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/history_list.py", line 302, in on_doubleclick
    self.parent.show_transaction(tx)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/main_window.py", line 810, in show_transaction
    show_transaction(tx, self, tx_desc)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/transaction_dialog.py", line 57, in show_transaction
    d = TxDialog(tx, parent, desc, prompt_if_unsaved)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/transaction_dialog.py", line 163, in __init__
    self.update()
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/transaction_dialog.py", line 256, in update
    fee = self.tx.get_fee()
  File "/Users/cryptopoly/cb-client-wallet/electrum/transaction.py", line 1153, in get_fee
    return self.input_value() - self.output_value()
  File "/Users/cryptopoly/cb-client-wallet/electrum/transaction.py", line 1140, in input_value
    return sum(x['value'] for x in self.inputs())
  File "/Users/cryptopoly/cb-client-wallet/electrum/transaction.py", line 1140, in <genexpr>
    return sum(x['value'] for x in self.inputs())

**Comment by cryptopoly** [comment]
Fixed by @tomt1664
