### ISSUE TITLE
redemption: Error loading exported redemption transaction

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/cb-client-wallet#48]
Traceback (most recent call last):
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/main_window.py", line 2528, in do_process_from_file
    self.show_transaction(tx)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/main_window.py", line 810, in show_transaction
    show_transaction(tx, self, tx_desc)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/transaction_dialog.py", line 57, in show_transaction
    d = TxDialog(tx, parent, desc, prompt_if_unsaved)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/transaction_dialog.py", line 163, in __init__
    self.update()
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/transaction_dialog.py", line 256, in update
    fee = self.tx.get_fee()
  File "/Users/cryptopoly/cb-client-wallet/electrum/transaction.py", line 1148, in get_fee
    return self.input_value() - self.output_value()
  File "/Users/cryptopoly/cb-client-wallet/electrum/transaction.py", line 1136, in input_value
    return sum(x['value'] for x in self.inputs())
  File "/Users/cryptopoly/cb-client-wallet/electrum/transaction.py", line 1136, in 
    return sum(x['value'] for x in self.inputs())
KeyError: 'value'
 
Additional information
Electrum version: 3.2.2-259-g8195be86-dirty 
Python version: 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
Operating system: Darwin-18.6.0-x86_64-i386-64bit 
Wallet type: standard 
Locale: en_GB

**Comment by nkostoulas** [comment]
fixed
