### ISSUE TITLE
Spend from registered address button not working

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/cb-client-wallet#54]
No action when spend from registered address is triggered

Last login: Tue Jul  9 11:54:00 on ttys002
cryptopolys-MacBook-Pro-2:~ cryptopoly$ /Users/cryptopoly/DGLD-Scripts/MacOS/DGLD_Electrum/TEST_Electrum_Client_Wallet.command ; exit;
[ecc] warning: libsecp256k1 library not available, falling back to python-ecdsa
Traceback (most recent call last):
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/main_window.py", line 1323, in do_update_fee
    tx = make_tx(fee_estimator)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/main_window.py", line 1321, in <lambda>
    fixed_fee=fee_est, is_sweep=is_sweep, b_allow_zerospend=b_allow_zerospend)
  File "/Users/cryptopoly/cb-client-wallet/electrum/wallet.py", line 615, in make_unsigned_transaction
    fee_estimator, self.dust_threshold(), b_allow_zerospend)
  File "/Users/cryptopoly/cb-client-wallet/electrum/coinchooser.py", line 261, in make_tx
    change = self.change_outputs(tx, change_addrs, fee, dust_threshold)
  File "/Users/cryptopoly/cb-client-wallet/electrum/coinchooser.py", line 174, in change_outputs
    dust_threshold)
  File "/Users/cryptopoly/cb-client-wallet/electrum/coinchooser.py", line 122, in change_amounts
    max_change = max(max(output_amounts) * 1.25, 0.02 * COIN)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/main_window.py", line 1323, in do_update_fee
    tx = make_tx(fee_estimator)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/main_window.py", line 1321, in <lambda>
    fixed_fee=fee_est, is_sweep=is_sweep, b_allow_zerospend=b_allow_zerospend)
  File "/Users/cryptopoly/cb-client-wallet/electrum/wallet.py", line 615, in make_unsigned_transaction
    fee_estimator, self.dust_threshold(), b_allow_zerospend)
  File "/Users/cryptopoly/cb-client-wallet/electrum/coinchooser.py", line 261, in make_tx
    change = self.change_outputs(tx, change_addrs, fee, dust_threshold)
  File "/Users/cryptopoly/cb-client-wallet/electrum/coinchooser.py", line 174, in change_outputs
    dust_threshold)
  File "/Users/cryptopoly/cb-client-wallet/electrum/coinchooser.py", line 122, in change_amounts
    max_change = max(max(output_amounts) * 1.25, 0.02 * COIN)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/main_window.py", line 1323, in do_update_fee
    tx = make_tx(fee_estimator)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/main_window.py", line 1321, in <lambda>
    fixed_fee=fee_est, is_sweep=is_sweep, b_allow_zerospend=b_allow_zerospend)
  File "/Users/cryptopoly/cb-client-wallet/electrum/wallet.py", line 615, in make_unsigned_transaction
    fee_estimator, self.dust_threshold(), b_allow_zerospend)
  File "/Users/cryptopoly/cb-client-wallet/electrum/coinchooser.py", line 261, in make_tx
    change = self.change_outputs(tx, change_addrs, fee, dust_threshold)
  File "/Users/cryptopoly/cb-client-wallet/electrum/coinchooser.py", line 174, in change_outputs
    dust_threshold)
  File "/Users/cryptopoly/cb-client-wallet/electrum/coinchooser.py", line 122, in change_amounts
    max_change = max(max(output_amounts) * 1.25, 0.02 * COIN)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/main_window.py", line 1323, in do_update_fee
    tx = make_tx(fee_estimator)
  File "/Users/cryptopoly/cb-client-wallet/electrum/gui/qt/main_window.py", line 1321, in <lambda>
    fixed_fee=fee_est, is_sweep=is_sweep, b_allow_zerospend=b_allow_zerospend)
  File "/Users/cryptopoly/cb-client-wallet/electrum/wallet.py", line 615, in make_unsigned_transaction
    fee_estimator, self.dust_threshold(), b_allow_zerospend)
  File "/Users/cryptopoly/cb-client-wallet/electrum/coinchooser.py", line 261, in make_tx
    change = self.change_outputs(tx, change_addrs, fee, dust_threshold)
  File "/Users/cryptopoly/cb-client-wallet/electrum/coinchooser.py", line 174, in change_outputs
    dust_threshold)
  File "/Users/cryptopoly/cb-client-wallet/electrum/coinchooser.py", line 122, in change_amounts
    max_change = max(max(output_amounts) * 1.25, 0.02 * COIN)
ValueError: max() arg is an empty sequence

**Comment by goodship1** [comment]
Hi is it okay to try and pick this issue up ?

**Comment by cryptopoly** [comment]
Thanks for the offer! @tomt1664 what say ye? :D

**Comment by nkostoulas** [comment]
It will be a little hard to re-create given that there are no public cb electrum servers at the moment. You could setup your own server and blockchain, which is a bit involved, but we can offer some assistance if you're willing to do that!

**Comment by cryptopoly** [comment]
@goodship1 I'm testing at the mo and almost created a packaged zip file... I use that term loosely but it's a fully config'd and ready to go, ocean chain and wallets etc

**Comment by goodship1** [comment]
Thanks for the reply's. I don't mind setting up my own Server and Blockchain. @nkostoulas  @cryptopoly

**Comment by nkostoulas** [comment]
Can't seem to be able to recreate this. Leaving this open till fully resolved.
