### ISSUE TITLE
Wallet Crash - Crashed but wallets stayed open

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/cb-client-wallet#68]
Error report received - was not doing anything with wallets (or related files) at the time but crash report popped up

Traceback
Traceback (most recent call last):
  File "/Users/cryptopoly/DGLD/cb-client-wallet/electrum/util.py", line 856, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/Users/cryptopoly/DGLD/cb-client-wallet/electrum/network.py", line 1102, in run
    self.wait_on_sockets()
  File "/Users/cryptopoly/DGLD/cb-client-wallet/electrum/network.py", line 1078, in wait_on_sockets
    self.process_responses(interface)
  File "/Users/cryptopoly/DGLD/cb-client-wallet/electrum/network.py", line 732, in process_responses
    self.process_response(interface, response, callbacks)
  File "/Users/cryptopoly/DGLD/cb-client-wallet/electrum/network.py", line 672, in process_response
    self.on_get_header(interface, response)
  File "/Users/cryptopoly/DGLD/cb-client-wallet/electrum/network.py", line 924, in on_get_header
    chain = blockchain.check_header(header)
  File "/Users/cryptopoly/DGLD/cb-client-wallet/electrum/blockchain.py", line 174, in check_header
    if b.check_header(header):
  File "/Users/cryptopoly/DGLD/cb-client-wallet/electrum/blockchain.py", line 227, in check_header
    return header_hash == self.get_hash(height)
  File "/Users/cryptopoly/DGLD/cb-client-wallet/electrum/blockchain.py", line 453, in get_hash
    return hash_header(self.read_header(height))
  File "/Users/cryptopoly/DGLD/cb-client-wallet/electrum/blockchain.py", line 431, in read_header
    self.assert_headers_file_available(name)
  File "/Users/cryptopoly/DGLD/cb-client-wallet/electrum/blockchain.py", line 361, in assert_headers_file_available
    raise FileNotFoundError('Electrum headers_dir does not exist. Was it deleted while running?')
FileNotFoundError: Electrum headers_dir does not exist. Was it deleted while running?
 
Additional information
Electrum version: 3.2.2-286-g483d6b89-dirty 
Python version: 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
Operating system: Darwin-19.0.0-x86_64-i386-64bit 
Wallet type: standard 
Locale: en_GB

**Comment by nkostoulas** [comment]
Looks like you deleted the headers dir
