### ISSUE TITLE
core: Intermittent error in verify_header_proof

### ISSUE THREAD

**Issue by lawlawlaw** [commerceblock/cb-client-wallet#98]
The following error message appeared in the terminal:

Traceback (most recent call last):
  File "/Users/lawrence/Projects/cb-client-wallet/electrum/util.py", line 856, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/Users/lawrence/Projects/cb-client-wallet/electrum/network.py", line 1102, in run
    self.wait_on_sockets()
  File "/Users/lawrence/Projects/cb-client-wallet/electrum/network.py", line 1078, in wait_on_sockets
    self.process_responses(interface)
  File "/Users/lawrence/Projects/cb-client-wallet/electrum/network.py", line 732, in process_responses
    self.process_response(interface, response, callbacks)
  File "/Users/lawrence/Projects/cb-client-wallet/electrum/network.py", line 637, in process_response
    self.on_notify_header(interface, result)
  File "/Users/lawrence/Projects/cb-client-wallet/electrum/network.py", line 1136, in on_notify_header
    b = blockchain.can_connect(header)
  File "/Users/lawrence/Projects/cb-client-wallet/electrum/blockchain.py", line 180, in can_connect
    if b.can_connect(header):
  File "/Users/lawrence/Projects/cb-client-wallet/electrum/blockchain.py", line 474, in can_connect
    if not verify_header_proof(header):
  File "/Users/lawrence/Projects/cb-client-wallet/electrum/blockchain.py", line 86, in verify_header_proof
    parse_scriptSig(d, bytearray.fromhex(proof+pushdata+challenge))
  File "/Users/lawrence/Projects/cb-client-wallet/electrum/transaction.py", line 413, in parse_scriptSig
    m, n, x_pubkeys, pubkeys, redeem_script = parse_redeemScript_multisig(redeem_script_unsanitized)
  File "/Users/lawrence/Projects/cb-client-wallet/electrum/transaction.py", line 470, in parse_redeemScript_multisig
    dec2 = [ x for x in script_GetOp(redeem_script) ]
  File "/Users/lawrence/Projects/cb-client-wallet/electrum/transaction.py", line 470, in <listcomp>
    dec2 = [ x for x in script_GetOp(redeem_script) ]
  File "/Users/lawrence/Projects/cb-client-wallet/electrum/transaction.py", line 304, in script_GetOp
    (nSize,) = struct.unpack_from('<I', _bytes, i)
struct.error: unpack_from requires a buffer of at least 4 bytes

It appears as though ~~a transaction~~ **a header proof** was truncated.
The error message did not repeat on clicking 'rescan blockchain'.

**Comment by tomt1664** [comment]
I don't think it is a transaction - seems to be an issue with the block header challenge script. Did anything precipitate it?

**Comment by lawlawlaw** [comment]
No that I'm aware of. It was sitting idle, connected to the server.
